### ISSUE TITLE
Self trained network

### ISSUE THREAD

**Issue by WangJYao** [songc42/Feature-proliferation#1]
请问，对于我自己训练的stylegan网络，我应该如何改善他的出图质量呢

**Comment by songc42** [comment]
You can simply apply **truncation**, or follow our strategy:
 1, Record the distribution of each feature map of self-trained StyleGAN generator, this distribution is characterised by mean value &mu; and standard deviation &sigma;  as we claimed in paper ** Section 4.1**
 2, Usee equation 3 to determine the risky feature maps
 3, Follow **Section 4.2** to rescale risky features

**Comment by WangJYao** [comment]
谢谢您的答复！
我能理解为每次输出一张图像时，都要记录每一层的特征图的分布，然后缩放风险特征，最后重新生成一张改善后的图片吗？
请问，在您的代码库中有相关的代码吗？

**Comment by songc42** [comment]
1，这个分布指的是，对于每一个feature map，如第一层的第三个feature map，记录他的分布，需要多次生成图片，如生成三千次的图片。记录这个feature map在这三千次生成中的均值的分布，构成这个feature map的distribution。
2，确定好每个feature map的分布后，然后就可以通过这些分布对每一次新的输出进行风险特征的缩放。
3，在我的代码中FFHQ_var就是记录着计算好的每个特征图的分布，在training/modify_networks.py里面就有缩放相关的代码

**Comment by WangJYao** [comment]
非常感谢您的答复，
在您的解答和代码的帮助下，我已经知道如何实现特征缩放了，
请问有生成三千次图片并记录feature map的分布的相关代码吗？
conv0_vari_b1.txt等文件保存的是feature map的标准差还是方差？
期待您的回复！
